name: Build Vue Component

on:
  push:
    branches:
      - main  # oder dein Branch-Name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Vue component
        run: node build-vue.js

    
